---
services:
  sadasadam:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
    # Modify the paths below to point to your local data and config directories
      # - /local/path/to/data:/src/data
      # - /local/path/to/config_dir:/src/config
      - /home/jpischke/geodata/sadasadam_data_test_2:/src/data
    env_file:
      - .env
